---

name: shellcheck
on:
  push:
    paths:
    - '**.sh'
    - '.github/workflows/shellcheck.yml'
  pull_request:
    paths:
    - '**.sh'
    - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: shellcheck
    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error

...
